// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalCarService.Api;

namespace RentalCarService.Api.Migrations
{
    [DbContext(typeof(RentalContext))]
    partial class RentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("RentalCarService.Api.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BookingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarCategoryID")
                        .HasColumnType("int");

                    b.Property<int>("CarID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerDateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MilageRegistrated")
                        .HasColumnType("int");

                    b.Property<int>("MilageReturned")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("RentalEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentalStart")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingID");

                    b.ToTable("Booking");

                    b.HasData(
                        new
                        {
                            BookingID = 12,
                            BookingNumber = "125040",
                            CarCategoryID = 2,
                            CarID = 3,
                            CustomerDateOfBirth = "1212121212",
                            MilageRegistrated = 15270,
                            MilageReturned = 0,
                            Price = 0.0,
                            RentalEnd = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentalStart = new DateTime(2021, 1, 18, 18, 22, 53, 162, DateTimeKind.Local).AddTicks(546)
                        });
                });

            modelBuilder.Entity("RentalCarService.Api.Models.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Booked")
                        .HasColumnType("bit");

                    b.Property<int>("CarTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Milage")
                        .HasColumnType("int");

                    b.Property<string>("Regnr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarID = 1,
                            Booked = false,
                            CarTypeID = 2,
                            Milage = 25800,
                            Regnr = "CPR100"
                        },
                        new
                        {
                            CarID = 2,
                            Booked = false,
                            CarTypeID = 1,
                            Milage = 100000,
                            Regnr = "BXR995"
                        },
                        new
                        {
                            CarID = 3,
                            Booked = true,
                            CarTypeID = 3,
                            Milage = 15270,
                            Regnr = "RON222"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
